### ISSUE TITLE
Wrong log color in GitHub Actions console

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/kaskadi-cli#13]
**Issue**

Color in console log for _GitHub Actions_ doesn't seem to behave the same as in the terminal on PC. Instead of having the text colored, there is a pink background on the zone where the color is applied which makes the text hardly visible

**Steps to reproduce**
- start creating a new repo in Kaskadi
- choose one of the template to base your repo on
- choose a name (doesn't matter which one)
- choose a repo type (doesn't matter)
- once created, wait a little and then go into _Actions_
- wait until the `init` action shows up and then go into it to see the console feedback
- in the `Init` step you should see the pink background coloring appear

**It's here for reference, I will have a look at it tomorrow if I have time!** :nerd_face:

**Comment by Holger-Will** [comment]
does not matter, don't worry. the github console is probably just a 16 or 256 Color terminal, whereas the color module assumes 32-Bit colors. The console colors are not important for automated runs ;-)

**Comment by Holger-Will** [comment]
I have created a separate repo/package for the color module. we can continue the discussion there...
color detection could be done like this: ps://unix.stackexchange.com/questions/23763/checking-how-many-colors-my-terminal-emulator-supports

**Comment by alexlemaire** [comment]
Closing here since discussion takes place in the other issue
