### ISSUE TITLE
add functionality to force check a patch by LGTM

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-cli#7]
> LGTM is generating a report the first time we follow a repo.
> It also does automatic reporting on pull requests but not on push.
> 
> So in order to get an updated report for each push, we can implement automated LGTM API calls following this doc

add functionality to force check an patch by LGTM

**Comment by alexlemaire** [comment]
Now using static code analysis provided by GitHub inside of our workflow. They use CodeQL query language and run the same queries as LGTM does (they developed their analyzer in collaboration with Semmle/LGTM).

Feature not necessary anymore, closing.
