### ISSUE TITLE
npm publish automation

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-cli#8]
add a github action that publishes automatically on npm.

it should check if `npm show kaskadi-cli version` is different from the one in `npm version` and run `npm version patch` if they are the same otherwise use the version from package.json...

**Comment by alexlemaire** [comment]
Taking care of this

**Comment by alexlemaire** [comment]
Automation in place.

Currently it's trigger only on `master` and `release/**` branches for commits affecting `kaskadi` or anything in the `functions` folder.

Closing for now.
